Notebook Extension Test Update
dataflownb/dfnotebook-extension pull request #27
Opened 2024-05-11 17:49 UTC by colinjbrown

This is a work in progress, this should update all of our tests to actually test the notebook-extension.

Currently working tests:
- Dfcells package    **ALL**
- Dfnotebook package **REWRITES REQUIRED**
- Dfgraph package **WIP**
- Dfoutputarea **Some Tests Exit Successfully**

2024-06-10 19:44 UTC, dakoop commented
Seeing an error. Ran `jlpm install` followed by `jlpm build:test`

```
❯ jlpm build:test
(node:13622) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
lerna notice cli v8.1.3
lerna info versioning independent

   ✔  @dfnotebook/dfgraph:build:test (3s)
   ✔  @dfnotebook/dfoutputarea:build:test (4s)

———————————————————————————————————————————————————————————————————————————————
   ✖  @dfnotebook/dfcells:build:test
      src/widget.ts(351,22): error TS2339: Property 'createGraph' does not exist on type 'GraphManager'.
      test/widget.spec.ts(31,29): error TS2307: Cannot find module '@dfnotebook/dfcells/lib/testutils' or its corresponding type declarations.
```

2024-06-11 21:17 UTC, dakoop commented
Needed to do a `jlpm:build` before building the tests since `testutils.ts` is in the dfnotebook package.

2024-06-12 05:08 UTC, dakoop requested changes
In addition, the dfgraph tests seem to fail with an error:
```
@dfnotebook/dfgraph: Error: Could not resolve a module for a custom reporter.
@dfnotebook/dfgraph:   Module name: github-actions
@dfnotebook/dfgraph:     at dfnotebook-extension/node_modules/jest-config/build/normalize.js:558:15
@dfnotebook/dfgraph:     at Array.map (<anonymous>)
@dfnotebook/dfgraph:     at normalizeReporters
```
I believe these tests are yet to be added, but perhaps we can add a stub so the package can run without error?

2024-06-12 05:08 UTC, dakoop commented on tsconfigbase.json
This change does not seem necessary nor does it match jupyterlab

2024-06-12 05:16 UTC, colinjbrown commented on packages/dfnotebook-extension/src/index.ts
This was the removal of an old unneeded comment that was resolved by an older update, you want the comment back in? While out of scope of this update that seems somewhat silly unless you want me to cherrypick that onto master.

2024-06-12 17:06 UTC, colinjbrown commented on package-lock.json
This was a remnant of trying to resolve issues with the Jupyterlab staging version of yarn, it has been removed.

2024-06-12 20:47 UTC, colinjbrown commented on packages/dfoutputarea/src/widget.ts
We've had discussions about this off Github, this will be moved to a seperate PR if SimplifiedOutputArea support is added.

2024-06-12 20:50 UTC, colinjbrown commented on packages/dfcells/src/widget.ts
This was named testflag as this was the only known way to reach a graph not being defined, I've renamed as suggested for consistency though.

2024-06-12 21:12 UTC, colinjbrown commented on tsconfigbase.json
Removed, this was part of the jest changes that was pulled in because there were issues with non ts files that weren't being recognized when build, this has since been fixed so it is no longer needed.

2024-06-14 05:47 UTC, dakoop commented on packages/dfnotebook-extension/src/index.ts
Understand this cleanup is not a big deal. Just trying to separate changes to the core code from test additions in the PR.

2024-06-14 05:48 UTC, merged